version: '3.5'
services:
    meetplanapp:
        build: subrepositories/MeetPlan
        volumes:
            - ./MeetPlanDB:/db
        networks:
            meetplan:
                aliases:
                    - meetplan
    nginx-proxy:
        depends_on:
            - meetplanapp
        image: nginx:alpine
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            meetplan:
                aliases:
                    - nginx
        ports:
            - "80:80"
networks:
    meetplan:
